name: CI Refcard

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened]

jobs:
    build:
        runs-on: ubuntu-22.04 ## Job machine uses specific version, as latest might cause newer ubuntu versions, which might break the code compatibility
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - run: npm i
            - run: npm run build
            - run: ls -la build
